src/main/java/ru/sadkov/tm/model/AbstractEntity.java
package ru.sadkov.tm.model;

import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import ru.sadkov.tm.model.enumerate.Status;

import javax.persistence.*;
import java.util.Date;

@MappedSuperclass
@Getter
@Cacheable
@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Setter
public abstract class AbstractEntity {

    @NotNull
    @Id
    String id;

    @NotNull
    @Column(name = "name")
    String name;

    @Nullable
    @Column(name = "description")
    String description;

    @NotNull
    @Column(name = "date_create")
    @Temporal(TemporalType.DATE)
    Date dateCreate;

    @Nullable
    @Column(name = "date_begin")
    @Temporal(TemporalType.DATE)
    Date dateBegin;

    @Nullable
    @Column(name = "date_end")
    @Temporal(TemporalType.DATE)
    Date dateEnd;

    @NotNull
    @Enumerated(value = EnumType.STRING)
    Status status;

}

src/main/java/ru/sadkov/tm/model/Project.java
package ru.sadkov.tm.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import ru.sadkov.tm.model.enumerate.Status;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Getter
@Setter
@NoArgsConstructor
@Entity
//@Cacheable
//@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "projects")
public final class Project extends AbstractEntity {

    @NotNull
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    private User user;

    @Nullable
    @OneToMany(mappedBy = "project", cascade = CascadeType.REMOVE, orphanRemoval = true)
    @org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    private List<Task> tasks;


    public Project(@NotNull final String name, @Nullable final String description, @NotNull String id) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.dateCreate = new Date();
        this.dateBegin = new Date();
        this.dateEnd = new Date();
        this.status = Status.PLANNED;
    }

    @Override
    public String toString() {
        return "Project{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", dateCreate=" + dateCreate +
                ", dateBegin=" + dateBegin +
                ", dateEnd=" + dateEnd +
                ", status=" + status +
                '}';
    }
}

src/main/java/ru/sadkov/tm/model/Task.java
package ru.sadkov.tm.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.jetbrains.annotations.NotNull;

import ru.sadkov.tm.model.enumerate.Status;

import javax.persistence.*;
import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
@Entity
//@Cacheable
//@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@Table(name = "tasks")
public final class Task extends AbstractEntity {

    @NotNull
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "project_id")
    private Project project;


    public Task(@NotNull final String id, @NotNull final String name, @NotNull final Project project, @NotNull final String description) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.project = project;
        this.dateEnd = new Date();
        this.dateBegin = new Date();
        this.dateCreate = new Date();
        this.status = Status.PLANNED;
    }

    @Override
    public String toString() {
        return "Task{" +
                "projectId='" + project.getId() + '\'' +
                ", id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", description='" + description + '\'' +
                ", dateCreate=" + dateCreate +
                ", dateBegin=" + dateBegin +
                ", dateEnd=" + dateEnd +
                ", status=" + status +
                '}';
    }
}

src/main/java/ru/sadkov/tm/model/User.java
package ru.sadkov.tm.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CacheConcurrencyStrategy;
import org.jetbrains.annotations.Nullable;
import ru.sadkov.tm.model.enumerate.Role;

import javax.persistence.*;
import java.util.List;

@Getter
@Setter
//@Cacheable
//@org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
@NoArgsConstructor
@Entity
@Table(name = "users")
public final class User {

    @Id
    private String id;

    @Column(name = "login", unique = true)
    private String login;

    private String password;

    @Nullable
    @OneToMany(fetch = FetchType.EAGER, mappedBy = "user", cascade = CascadeType.REMOVE, orphanRemoval = true)
    @org.hibernate.annotations.Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    private List<Project> projectList;

    @Enumerated(value = EnumType.ORDINAL)
    private Role role;

    public User(@Nullable String login, @Nullable String password, @Nullable Role role) {
        this.login = login;
        this.password = password;
        this.role = role;
    }

    @Override
    public String toString() {
        return "User{" +
                "id='" + id + '\'' +
                ", login='" + login + '\'' +
                ", password='" + password + '\'' +
                ", role=" + role +
                '}';
    }
}

src/main/java/ru/sadkov/tm/model/bean/ProjectBean.java
package ru.sadkov.tm.model.bean;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.springframework.security.core.context.SecurityContextHolder;
import ru.sadkov.tm.model.Project;
import ru.sadkov.tm.model.Task;
import ru.sadkov.tm.model.User;
import ru.sadkov.tm.model.enumerate.Status;
import ru.sadkov.tm.service.IProjectService;
import ru.sadkov.tm.service.IUserService;

import javax.faces.bean.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.Date;
import java.util.List;

@Named(value = "project")
@SessionScoped
@Getter
@Setter
@NoArgsConstructor
public class ProjectBean {

    @Inject
    private IProjectService projectService;

    @Inject
    private IUserService userService;

    @Nullable
    List<Task> taskList;
    @Nullable
    String id;
    @Nullable
    String name;
    @Nullable
    String description;
    @Nullable
    Date dateCreate;
    @Nullable
    Date dateBegin;
    @Nullable
    Date dateEnd;
    @Nullable
    Status status;
    @Nullable
    String userId;
    @Nullable
    Project currentProject;

    private void clear() {
        taskList = null;
        id = null;
        name = null;
        description = null;
        dateCreate = null;
        dateBegin = null;
        dateEnd = null;
        status = null;
        userId = null;
        currentProject = null;
    }

    @NotNull
    public String saveProject(@NotNull final ProjectBean projectBean,@NotNull final String userId) {
        projectService.persist(userId, projectBean.name, projectBean.description);
        clear();
        return "/projects.xhtml?faces-redirect=true";
    }

    @NotNull
    public List<Project> getProjects() {
        @NotNull final String username = SecurityContextHolder.getContext().getAuthentication().getName();
        return projectService.findProjectsByUser(username);
    }

    @NotNull
    public String showProject(@NotNull final String projectId) {
        currentProject = projectService.findOne(projectId);
        return "/project.xhtml?faces-redirect=true";
    }

    @NotNull
    public String delete(@NotNull final String projectId) {
        projectService.remove(projectId);
        return "/projects.xhtml?faces-redirect=true";
    }

    @NotNull
    public String start(@NotNull final String projectName) {
        projectService.startProject(projectName);
        return "/projects.xhtml?faces-redirect=true";
    }

    @NotNull
    public String end(@NotNull final String projectName) {
        projectService.endProject(projectName);
        return "/projects.xhtml?faces-redirect=true";
    }

    @NotNull
    public String update(@NotNull final String projectId) {
        currentProject = projectService.findOne(projectId);
        return "/pUpdate.xhtml?faces-redirect=true";
    }

    @NotNull
    public String updateProject(@NotNull final ProjectBean projectBean,@NotNull final String projectId) {
        projectService.update(projectId, projectBean.name, projectBean.description);
        clear();
        return "/projects.xhtml?faces-redirect=true";
    }

    @NotNull
    public String showTasks(@NotNull final String projectId) {
        currentProject = projectService.findOne(projectId);
        return "/tasks.xhtml?faces-redirect=true";
    }

    @NotNull
    public String createTask(@NotNull final String projectId) {
        currentProject = projectService.findOne(projectId);
        return "/taskCreate.xhtml?faces-redirect=true";
    }
}

src/main/java/ru/sadkov/tm/model/bean/TaskBean.java
package ru.sadkov.tm.model.bean;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import ru.sadkov.tm.model.Task;
import ru.sadkov.tm.model.enumerate.Status;
import ru.sadkov.tm.service.ITaskService;

import javax.faces.bean.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.Date;
import java.util.List;

@Named(value = "task")
@SessionScoped
@Getter
@Setter
@NoArgsConstructor
public class TaskBean {

    @Inject
    private ITaskService taskService;

    @Nullable
    String id;
    @Nullable
    String name;
    @Nullable
    String description;
    @Nullable
    Date dateCreate;
    @Nullable
    Date dateBegin;
    @Nullable
    Date dateEnd;
    @Nullable
    Status status;
    @Nullable
    Task currentTask;

    private void clear() {
        id = null;
        name = null;
        description = null;
        dateCreate = null;
        dateBegin = null;
        dateEnd = null;
        status = null;
        currentTask = null;
    }

    public List<Task> getTasks(@NotNull final String projectId) {
        return taskService.findAllByProjectId(projectId);
    }

    public String saveTask(@NotNull final TaskBean taskBean,@NotNull final String projectName) {
        taskService.saveTask(taskBean.name, projectName, taskBean.description);
        clear();
        return "/tasks.xhtml?faces-redirect=true";
    }

    public String showTask(@NotNull final String taskId) {
        currentTask = taskService.findOneById(taskId);
        return "/task.xhtml?faces-redirect=true";
    }

    public String delete(@NotNull final String taskId) {
        taskService.removeById(taskId);
        return "/tasks.xhtml?faces-redirect=true";
    }

    public String start(@NotNull final String taskName) {
        taskService.startTask(taskName);
        return "/tasks.xhtml?faces-redirect=true";
    }

    public String end(@NotNull final String taskName) {
        taskService.endTask(taskName);
        return "/tasks.xhtml?faces-redirect=true";
    }

    public String update(@NotNull final String taskId) {
        currentTask = taskService.findOneById(taskId);
        return "/tUpdate.xhtml?faces-redirect=true";
    }

    public String updateTask(@NotNull final TaskBean taskBean,@NotNull final String taskId) {
        taskService.update(taskId, taskBean.name, taskBean.description);
        clear();
        return "/tasks.xhtml?faces-redirect=true";
    }

}

src/main/java/ru/sadkov/tm/model/bean/UserBean.java
package ru.sadkov.tm.model.bean;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.springframework.security.core.context.SecurityContextHolder;
import ru.sadkov.tm.model.Project;
import ru.sadkov.tm.model.User;
import ru.sadkov.tm.model.enumerate.Role;
import ru.sadkov.tm.service.IUserService;

import javax.faces.bean.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;
import java.util.List;

@Named(value = "user")
@SessionScoped
@Getter
@Setter
@NoArgsConstructor
public class UserBean {

    @Inject
    @NotNull
    private IUserService userService;

    @Nullable
    private User currentUser;
    @Nullable
    private String id;
    @Nullable
    private String login;
    @Nullable
    private String password;
    @Nullable
    private List<Project> projectList;
    @Nullable
    private Role role;

    private void clearFields() {
        id = null;
        login = null;
        password = null;
        projectList = null;
        role = null;
    }

    @NotNull
    public String addUser() {
        @NotNull final User user = userService.createUser(login, password);
        userService.userRegister(user);
        clearFields();
        return "/index.xhtml";
    }

    @NotNull
    public String createProject() {
        @NotNull final String username = SecurityContextHolder.getContext().getAuthentication().getName();
        currentUser = userService.findOneByLogin(username);
        return "/projectCreate.xhtml";
    }

    @NotNull
    public String logout() {
        return "/index.xhtml";
    }

    @NotNull
    public boolean isAuth() {
        return SecurityContextHolder.getContext().getAuthentication().getName().equals("anonymousUser");
    }

    @NotNull
    public String getName() {
        if (isAuth()) return "GUEST";
        return SecurityContextHolder.getContext().getAuthentication().getName();
    }

}

src/main/java/ru/sadkov/tm/model/enumerate/Role.java
package ru.sadkov.tm.model.enumerate;

public enum Role {
    USER,
    ADMIN;

    Role() {
    }
}

src/main/java/ru/sadkov/tm/model/enumerate/Status.java
package ru.sadkov.tm.model.enumerate;

import org.jetbrains.annotations.NotNull;

public enum Status {

    PLANNED("запланировано"),
    PROCESS("в процессе"),
    DONE("готово");

    @NotNull
    private String displayName;

    Status(@NotNull final String displayName) {
        this.displayName = displayName;
    }

    @NotNull
    public String getDisplayName() {
        return displayName;
    }
}

src/main/java/ru/sadkov/tm/controller/LoginController.java
package ru.sadkov.tm.controller;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Controller
@RequestMapping("/login")
public class LoginController {

    @RequestMapping(method = RequestMethod.GET)
    public String loginPage(Model model) {
        return "login";
    }

}

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:sec="http://www.springframework.org/security/tags">

<f:view>
    <h:head>
        <h:outputStylesheet name="primeicons/primeicons.css" library="primefaces" />
        <title>Task Manager</title>
    </h:head>

    <h:body>
        <h:form>
            <p:growl id="TaskManager" showDetail="true"/>

            <p:toolbar>
                <f:facet name="left">
                    <p:commandButton action="index.xhtml?faces-redirect=true" type="submit" value="Main" icon="pi pi-home"/>

                    <p:commandButton action="projects?faces-redirect=true"  type="submit" value="Projects" icon="pi pi-folder-open"/>

                    <p:commandButton action="registration?faces-redirect=true" type="submit" value="Registration" icon="pi pi-user-plus"/>

                    <span class="ui-separator">
                <span class="ui-icon pi pi-ellipsis-v"/>
            </span>

                </f:facet>

                <f:facet name="right">
                    <f:facet name="right">
                        <p:commandButton ajax="false" action="login?faces-redirect=true" type="submit" value="Login" icon="pi pi-user"
                                         rendered="#{user.auth}"/>
                        <p:commandButton ajax="false" action="#{user.logout}" type="submit" value="Logout"
                                         icon="pi pi-user" rendered="#{!user.auth}"/>
                    </f:facet>
                </f:facet>

            </p:toolbar>
        </h:form>
        <h:form>
            <h2>Hello!</h2>
            <h:outputText value="#{user.name}"/>

        </h:form>
    </h:body>
</f:view>

</html>

src/main/webapp/pUpdate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">

<f:view>
    <h:head>
        <h:outputStylesheet name="primeicons/primeicons.css" library="primefaces"/>
        <title>Project create</title>
    </h:head>

    <h:body>
        <h:form>
            <p:growl id="TaskManager" showDetail="true"/>

            <p:toolbar>
                <f:facet name="left">
                    <p:commandButton action="index.xhtml?faces-redirect=true" type="submit" value="Main" icon="pi pi-home"/>

                    <p:commandButton action="projects?faces-redirect=true"  type="submit" value="Projects" icon="pi pi-folder-open"/>

                    <p:commandButton action="registration?faces-redirect=true" type="submit" value="Registration" icon="pi pi-user-plus"/>

                    <span class="ui-separator">
                <span class="ui-icon pi pi-ellipsis-v"/>
            </span>

                </f:facet>

                <f:facet name="right">
                    <f:facet name="right">
                        <p:commandButton ajax="false" action="login?faces-redirect=true" type="submit" value="Login" icon="pi pi-user"
                                         rendered="#{user.auth}"/>
                        <p:commandButton ajax="false" action="#{user.logout}" type="submit" value="Logout"
                                         icon="pi pi-user" rendered="#{!user.auth}"/>
                    </f:facet>
                </f:facet>

            </p:toolbar>
        </h:form>
        <h:form>
            <h:panelGrid columns="2" cellpadding="5">
                <p:outputLabel for="name" value="Project Name: "/>
                <p:inputText id="name" value="#{project.name}"/>

                <p:outputLabel for="description" value="Description: "/>
                <p:inputText id="description" value="#{project.description}"/>
                <h:form>
                    <p:commandButton ajax="false" action="#{project.updateProject(project,project.currentProject.id)}"
                                     type="submit" value="Edit Project"/>
                </h:form>
            </h:panelGrid>
        </h:form>
        <h:form>
            <p:commandButton ajax="false" type="submit" value="Back" action="projects?faces-redirect=true"/>
        </h:form>
    </h:body>
</f:view>
</html>

src/main/webapp/project.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">

<f:view>
    <h:head>
        <h:outputStylesheet name="primeicons/primeicons.css" library="primefaces"/>
        <title>Task Manager</title>
    </h:head>

    <h:body>
        <h:form>
            <p:growl id="TaskManager" showDetail="true"/>

            <p:toolbar>
                <f:facet name="left">
                    <p:commandButton action="index.xhtml?faces-redirect=true" type="submit" value="Main" icon="pi pi-home"/>

                    <p:commandButton action="projects?faces-redirect=true"  type="submit" value="Projects" icon="pi pi-folder-open"/>

                    <p:commandButton action="registration?faces-redirect=true" type="submit" value="Registration" icon="pi pi-user-plus"/>

                    <span class="ui-separator">
                <span class="ui-icon pi pi-ellipsis-v"/>
            </span>

                </f:facet>

                <f:facet name="right">
                    <f:facet name="right">
                        <p:commandButton ajax="false" action="login?faces-redirect=true" type="submit" value="Login" icon="pi pi-user"
                                         rendered="#{user.auth}"/>
                        <p:commandButton ajax="false" action="#{user.logout}" type="submit" value="Logout"
                                         icon="pi pi-user" rendered="#{!user.auth}"/>
                    </f:facet>
                </f:facet>

            </p:toolbar>
        </h:form>
        <br></br>
        <h:form id="form">
            <p:dataTable  id="basicDT" var="p" value="#{project.currentProject}">
                <f:facet name="header">
                    Project
                </f:facet>
                <p:column headerText="Id">
                    <h:outputText value="#{p.id}"/>
                </p:column>
                <p:column headerText="Name">
                    <h:outputText value="#{p.name}"/>
                </p:column>
                <p:column headerText="Description">
                    <h:outputText value="#{p.description}"/>
                </p:column>
                <p:column headerText="User">
                    <h:outputText value="#{p.user.login}"/>
                </p:column>
                <p:column headerText="Status">
                    <h:outputText value="#{p.status}"/>
                </p:column>
                <p:column headerText="Date Create">
                    <h:outputText value="#{p.dateCreate}"/>
                </p:column>
                <p:column headerText="Date Begin">
                    <h:outputText value="#{p.dateBegin}"/>
                </p:column>
                <p:column headerText="DateEnd">
                    <h:outputText value="#{p.dateEnd}"/>
                </p:column>
            </p:dataTable>
        </h:form>
        <br></br>
        <h:form>
            <p:commandButton ajax="false" type="submit" value="Back" action="projects?faces-redirect=true"/>
        </h:form>
    </h:body>
</f:view>
</html>

src/main/webapp/projectCreate.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">

<f:view>
    <h:head>
        <h:outputStylesheet name="primeicons/primeicons.css" library="primefaces"/>
        <title>Project create</title>
    </h:head>

    <h:body>
        <h:form>
            <p:growl id="TaskManager" showDetail="true"/>

            <p:toolbar>
                <f:facet name="left">
                    <p:commandButton action="index.xhtml?faces-redirect=true" type="submit" value="Main" icon="pi pi-home"/>

                    <p:commandButton action="projects?faces-redirect=true"  type="submit" value="Projects" icon="pi pi-folder-open"/>

                    <p:commandButton action="registration?faces-redirect=true" type="submit" value="Registration" icon="pi pi-user-plus"/>

                    <span class="ui-separator">
                <span class="ui-icon pi pi-ellipsis-v"/>
            </span>

                </f:facet>

                <f:facet name="right">
                    <f:facet name="right">
                        <p:commandButton ajax="false" action="login?faces-redirect=true" type="submit" value="Login" icon="pi pi-user"
                                         rendered="#{user.auth}"/>
                        <p:commandButton ajax="false" action="#{user.logout}" type="submit" value="Logout"
                                         icon="pi pi-user" rendered="#{!user.auth}"/>
                    </f:facet>
                </f:facet>

            </p:toolbar>
        </h:form>
        <h:form>
            <h:panelGrid columns="2" cellpadding="5">
                <p:outputLabel for="name" value="Project Name: "/>
                <p:inputText id="name" value="#{project.name}"/>

                <p:outputLabel for="description" value="Description: "/>
                <p:inputText id="description" value="#{project.description}"/>
                <h:form>
                    <p:commandButton ajax="false" action="#{project.saveProject(project,user.currentUser.id)}"
                                     type="submit" value="Add Project"/>
                </h:form>
            </h:panelGrid>
        </h:form>
        <h:form>
            <p:commandButton ajax="false" type="submit" value="Back" action="projects?faces-redirect=true"/>
        </h:form>
    </h:body>
</f:view>
</html>

src/main/webapp/registration.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui">

<f:view>
    <h:head>
        <h:outputStylesheet name="primeicons/primeicons.css" library="primefaces"/>
        <title>Task Manager</title>
    </h:head>

    <h:body>
        <h:form>
            <p:growl id="TaskManager" showDetail="true"/>

            <p:toolbar>
                <f:facet name="left">
                    <p:commandButton action="index.xhtml?faces-redirect=true" type="submit" value="Main" icon="pi pi-home"/>

                    <p:commandButton action="projects?faces-redirect=true"  type="submit" value="Projects" icon="pi pi-folder-open"/>

                    <p:commandButton action="registration?faces-redirect=true" type="submit" value="Registration" icon="pi pi-user-plus"/>

                    <span class="ui-separator">
                <span class="ui-icon pi pi-ellipsis-v"/>
            </span>

                </f:facet>

                <f:facet name="right">
                    <f:facet name="right">
                        <p:commandButton ajax="false" action="login?faces-redirect=true" type="submit" value="Login" icon="pi pi-user"
                                         rendered="#{user.auth}"/>
                        <p:commandButton ajax="false" action="#{user.logout}" type="submit" value="Logout"
                                         icon="pi pi-user" rendered="#{!user.auth}"/>
                    </f:facet>
                </f:facet>

            </p:toolbar>
        </h:form>
        <h:form>
            <h:panelGrid columns="2" cellpadding="5">
                <p:outputLabel for="login" value="Login: "/>
                <p:inputText id="login" value="#{user.login}"/>

                <p:outputLabel for="password" value="Password: "/>
                <p:inputText type="password" id="password" value="#{user.password}"/>
                <h:form>
                    <p:commandButton ajax="false" action="#{user.addUser}" type="submit" value="Add user"/>
                </h:form>
            </h:panelGrid>

        </h:form>
    </h:body>
</f:view>
</html>